# Cloudflare Pages Configuration
[build]
  command = "cd dashboard && npm install && npm run build"
  publish = "dashboard/dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_BASE_URL = "https://mcp-hub-worker.tito-7t.workers.dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
